# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: sensor.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'sensor.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0csensor.proto\x12\x06sensor\"R\n\rSensorRequest\x12\x11\n\tsensor_id\x18\x01 \x01(\t\x12\x0c\n\x04type\x18\x02 \x01(\t\x12\r\n\x05value\x18\x03 \x01(\x02\x12\x11\n\ttimestamp\x18\x04 \x01(\t\" \n\x0eSensorResponse\x12\x0e\n\x06status\x18\x01 \x01(\t2P\n\rSensorService\x12?\n\x0eSendSensorData\x12\x15.sensor.SensorRequest\x1a\x16.sensor.SensorResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'sensor_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_SENSORREQUEST']._serialized_start=24
  _globals['_SENSORREQUEST']._serialized_end=106
  _globals['_SENSORRESPONSE']._serialized_start=108
  _globals['_SENSORRESPONSE']._serialized_end=140
  _globals['_SENSORSERVICE']._serialized_start=142
  _globals['_SENSORSERVICE']._serialized_end=222
# @@protoc_insertion_point(module_scope)
